data:extend {
    {
        type = "double-setting",
        name = "rcc-multiplicative",
        setting_type = "runtime-global",
        default_value = 1.58,
        minimum_value = 0.0,
        order = "a-1",
    },
    {
        type = "double-setting",
        name = "rcc-additive",
        setting_type = "runtime-global",
        default_value = 0.0,
        order = "a-2",
    },
    {
        type = "double-setting",
        name = "rcc-maximum",
        setting_type = "runtime-global",
        default_value = 1000.0,
        minimum_value = 0.001,
        maximum_value = 1000.0,
        order = "b-1",
    },
    {
        type = "double-setting",
        name = "rcc-minimum",
        setting_type = "runtime-global",
        default_value = 0.001,
        minimum_value = 0.001,
        maximum_value = 1000.0,
        order = "b-2",
    },
    {
        type = "bool-setting",
        name = "rcc-print",
        setting_type = "runtime-global",
        default_value = true,
        order = "c",
    },
    {
        type = "int-setting",
        name = "rcc-print-precision",
        setting_type = "runtime-global",
        default_value = 1000,
        minimum_value = 1,
        order = "d",
    },
    {
        type = "int-setting",
        name = "rcc-fixed-cost",
        setting_type = "startup",
        default_value = 0,
        minimum_value = 0,
        order = "z",
    },
}
